{
  "hash": "bc3cab2bec035472416acdf60c84cc0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Alejandro Duque\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\nIn this lab, I will apply the spatial predictive modeling techniques demonstrated in the class exercise using a different 311 service request type of your choice as the predictor variable. I will build a complete spatial predictive model, document your process, and interpret your results.\n\n### Learning Objectives\n\nBy completing this assignment, you will demonstrate your ability to:\n\n-   Adapt example code to analyze a new dataset\n-   Build spatial features for predictive modeling\n-   Apply count regression techniques to spatial data\n-   Implement spatial cross-validation\n-   Interpret and communicate model results\n-   Critically evaluate model performance\n\n------------------------------------------------------------------------\n\n## Step 1: Choosing a 311 Violation Type\n\n### Getting the Data\n\nVacant buildings are a symptom of deeper urban disinvestment that shapes the daily lives of residents. Having spent time on the ground in communities where abandonment is not an abstraction but a lived reality, I chose this dataset because it speaks directly to the conditions that drive inequality in cities like Chicago. This analysis uses 2017 Chicago 311 vacant building reports to understand where vacancy concentrates and how well those patterns can be predicted.\n\n## Step 2: Complete the Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| message: false\n#| warning: false\n\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_vacant <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_vacant())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: /Users/alejandroduque/Documents/GitHub/CPLN5920_portfolio/labs/lab_4 \n```\n\n\n:::\n:::\n\n\n##### Reading the vacant buildings data and transforming into the correct Coordinate System\n\nBefore any analysis can begin, the data needs to be in the right shape and place. I loaded the 311 vacant buildings reports and filtered out any records missing location information. I then transformed the data into a projected coordinate system (ESRI:102271) specific to Illinois, which ensures that distance measurements are accurate in meters rather than degrees. Working in the wrong coordinate system is one of the most common mistakes in spatial analysis, and it will silently break everything downstream.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacant_buildings <- read_csv(here(\"labs/lab_4/data/311_vacant_buildings.csv\"))%>%\n  filter(!is.na(LATITUDE), !is.na(LONGITUDE)) %>%\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n\ncat(\"✓ Loaded vacant buildings\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded vacant buildings\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of calls:\", nrow(vacant_buildings), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of calls: 65073 \n```\n\n\n:::\n:::\n\n\n##### Loading in the Chicago Boundary\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n:::\n\n\n##### Visualizing where the vacant buildings are being reported\n\nThe point map shows each reported vacant building as a dot, giving a raw sense of where vacancy is concentrated across Chicago. The density surface smooths those points into a continuous heat map, making spatial patterns easier to read at a glance. Together, these two views reveal that vacancy is not randomly distributed but rather it clusters heavily on the west and south sides, perhaps reflecting decades of disinvestment in those communities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchi_bbox <- st_bbox(chicagoBoundary)\n\n\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = vacant_buildings, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  theme_void() +\n  coord_sf(\n        xlim = c(chi_bbox[\"xmin\"], chi_bbox[\"xmax\"]),\n    ylim = c(chi_bbox[\"ymin\"], chi_bbox[\"ymax\"])) +\n  labs(\n    title = \"Vacant Buildings Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(vacant_buildings))\n  )\n\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(vacant_buildings)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  coord_sf(\n        xlim = c(chi_bbox[\"xmin\"], chi_bbox[\"xmax\"]),\n    ylim = c(chi_bbox[\"ymin\"], chi_bbox[\"ymax\"])\n  ) +\n  theme_void() +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Vacant Buildings in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/visualize-points-1.png){width=960}\n:::\n:::\n\n\n#### Part 2: Fishnet Grid Creation\n\nI overlaid a 500m x 500m grid across Chicago and counted how many vacant buildings fall into each cell. This converts a cloud of points into a structured dataset where every cell has a count, including zeros. The choice of 500 meters reflects a scale that should be fine enough to capture neighborhood variation but coarse enough to avoid too many empty cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number()) %>%\n  st_transform('ESRI:102271') \n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\n\n##### Joining Fishnet and Building Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacant_buildings_fishnet <- st_join(vacant_buildings, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countvacant_buildings = n()) \n\nfishnet <- fishnet %>%\n  left_join(vacant_buildings_fishnet, by = \"uniqueID\") %>%\n  mutate(countvacant_buildings = replace_na(countvacant_buildings, 0))\n\ncat(\"\\nVacant Buildings count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVacant Buildings count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countvacant_buildings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    1.00    7.00   26.47   28.00  378.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero Vacant Buildings:\", \n    sum(fishnet$countvacant_buildings == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countvacant_buildings == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero Vacant Buildings: 542 / 2458 ( 22.1 %)\n```\n\n\n:::\n:::\n\n\n#### Part 3: Spatial Features\n\nA single count per cell tells you what is there, but not what surrounds it. K-nearest neighbor distance measures how close each grid cell is to the nearest vacant buildings, capturing the spatial context around each location. Cells near clusters of vacancy look different from isolated cases, and this feature helps the model learn that distinction. This kind of feature engineering is what separates a naive count model from one that actually understands space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\nvacant_coords <- st_coordinates(vacant_buildings)\n\nnn_result <- get.knnx(vacant_coords, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    vacant_buildings.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$vacant_buildings.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n   0.8906   78.5322  154.3599  261.9420  313.4905 1997.1337 \n```\n\n\n:::\n:::\n\n\n##### Local Moran's I & Hotspots\n\nLocal Moran's I answers if the vacancy I see in this cell part of a larger cluster, or is it a fluke? By comparing each cell to its neighbors, the statistic identifies High-High clusters (hot spots where vacancy surrounds vacancy), Low-Low clusters (cold spots), and spatial outliers. This matters because the west and south sides don't just have more vacant buildings, they have concentrated patterns of vacancy that simple counts alone cannot capture. The distance to hotspot variable built from this analysis gives the model a sense of how embedded each cell is in the broader geography of abandonment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  spatial_weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n    x <- as.numeric(data[[variable]])\n  \n  # Calculate Local Moran's I\nlocal_moran <- localmoran(x, spatial_weights, zero.policy = TRUE)\n\n  # Classify clusters\n  mean_val <- mean(x, na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & x > mean_val ~ \"High-High\",\n        local_i > 0 & x <= mean_val ~ \"Low-Low\",\n        local_i < 0 & x > mean_val ~ \"High-Low\",\n        local_i < 0 & x <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to vacant buildings\nfishnet <- calculate_local_morans(fishnet, \"countvacant_buildings\", k = 5)\n```\n:::\n\n\n##### Visualize Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Vacant Buildings Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_vacant()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to Vacant Buildings hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to Vacant Buildings hot spots\n  - Number of hot spot cells: 294 \n```\n\n\n:::\n:::\n\n\n#### Part 4: Count Regression Models\n\nI used Poisson regression, which is designed for count data. The model predicts vacancy as a function of nearest neighbor distance and distance to the nearest hot spot. These two features encode both local density and regional proximity to the worst-affected areas, giving the model the spatial intelligence it needs to make reasonable predictions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean modeling dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    countvacant_buildings,\n    vacant_buildings.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()  # Remove any remaining NAs\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\", ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson regression\nmodel_poisson <- glm(\n  countvacant_buildings ~ vacant_buildings.nn + dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countvacant_buildings ~ vacant_buildings.nn + dist_to_hotspot, \n    family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                        Estimate   Std. Error z value            Pr(>|z|)    \n(Intercept)          5.116131326  0.006487688   788.6 <0.0000000000000002 ***\nvacant_buildings.nn -0.010810037  0.000085470  -126.5 <0.0000000000000002 ***\ndist_to_hotspot     -0.000320698  0.000002934  -109.3 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 130117  on 2457  degrees of freedom\nResidual deviance:  23380  on 2455  degrees of freedom\nAIC: 31946\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n#### Part 5: Spatial Cross-Validation (2017)\n\nLeave One Group Out cross-validation divides the city into 10 spatial folds, trains the model on nine of them, and tests it on the one held out. This is repeated for every fold so that every cell gets predicted by a model that never saw it. The result is an honest estimate of how well the model generalizes across space. The MAE of 12.7 and RMSE of 26.5 tell us the model is making meaningful predictions, though the gap between those two numbers suggests it struggles most in the highest-vacancy cells.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nfishnet_model <- fishnet_model %>%\n  mutate(\n    spatial_group = kmeans(\n      cbind(\n        as.numeric(gsub(\".*_(\\\\d+)$\", \"\\\\1\", uniqueID)),  # extract x index\n        as.numeric(gsub(\"^(\\\\d+)_.*\", \"\\\\1\", uniqueID))   # extract y index\n      ),\n      centers = 10  # 10 spatial folds\n    )$cluster\n  )\n\nlogo_results <- map_dfr(unique(fishnet_model$spatial_group), function(group) {\n  \n  train <- fishnet_model %>% filter(spatial_group != group)\n  test  <- fishnet_model %>% filter(spatial_group == group)\n  \n  model <- glm(\n    countvacant_buildings ~ vacant_buildings.nn + dist_to_hotspot,\n    data = train,\n    family = \"poisson\"\n  )\n  \n  test %>%\n    mutate(\n      predicted = predict(model, newdata = test, type = \"response\"),\n      residual  = countvacant_buildings - predicted,\n      group     = group\n    ) %>%\n    dplyr::select(uniqueID, spatial_group, countvacant_buildings, predicted, residual, group)\n})\n\nmae  <- mean(abs(logo_results$residual))\nrmse <- sqrt(mean(logo_results$residual^2))\n\ncat(\"✓ Spatial Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Spatial Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Folds:\", length(unique(fishnet_model$spatial_group)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Folds: 10 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - MAE: \", round(mae, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - MAE:  12.707 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - RMSE:\", round(rmse, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - RMSE: 26.489 \n```\n\n\n:::\n:::\n\n\n#### Part 6: Model Evaluation\n\nComparing the Poisson model against this baseline answers the question: does the added complexity of regression actually buy us anything? In this case, the KDE outperformed the Poisson model (MAE: 8.3 vs 12.7), which is a humbling but honest result. KDE has an inherent advantage when predicting the same year's data because it directly reflects where buildings were reported. The real test of the regression model's value would be predicting a future year, where KDE loses its advantage and the model's learned relationships would need to carry the weight.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(spatstat)\n\nchicago_owin <- as.owin(st_transform(chicagoBoundary, st_crs(vacant_buildings)))\nvb_coords <- st_coordinates(vacant_buildings)\n\nvb_ppp <- ppp(\n  x = vb_coords[, 1],\n  y = vb_coords[, 2],\n  window = chicago_owin\n)\n\nkde_surface <- density(vb_ppp, sigma = bw.diggle(vb_ppp))\n\nfishnet_centroids <- st_centroid(fishnet) %>%\n  st_coordinates()\n\nkde_values <- spatstat.geom::interp.im(\n  kde_surface,\n  fishnet_centroids[, 1],\n  fishnet_centroids[, 2]\n)\n\nfishnet_eval <- fishnet %>%\n  mutate(kde_pred = kde_values) %>%\n  left_join(\n    logo_results %>% dplyr::select(uniqueID, predicted, residual),\n    by = \"uniqueID\"\n  ) %>%\n  filter(!is.na(kde_pred), !is.na(predicted))\n\nfishnet_eval <- fishnet_eval %>%\n  mutate(\n    kde_pred_scaled = kde_pred * (sum(countvacant_buildings) / sum(kde_pred, na.rm = TRUE)),\n    kde_residual    = countvacant_buildings - kde_pred_scaled\n  )\n\nkde_mae  <- mean(abs(fishnet_eval$kde_residual), na.rm = TRUE)\nkde_rmse <- sqrt(mean(fishnet_eval$kde_residual^2, na.rm = TRUE))\n\ncomparison <- data.frame(\n  Model = c(\"Poisson (LOGO-CV)\", \"KDE Baseline\"),\n  MAE   = round(c(mae, kde_mae), 3),\n  RMSE  = round(c(rmse, kde_rmse), 3)\n)\n\nprint(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Model    MAE   RMSE\n1 Poisson (LOGO-CV) 12.707 26.489\n2      KDE Baseline  8.322 16.175\n```\n\n\n:::\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet_eval, aes(fill = predicted), color = NA) +\n  scale_fill_viridis_c(option = \"plasma\", name = \"Predicted\") +\n  theme_void() +\n  labs(title = \"Poisson Model Predictions\")\n\np2 <- ggplot() +\n  geom_sf(data = fishnet_eval, aes(fill = kde_pred_scaled), color = NA) +\n  scale_fill_viridis_c(option = \"plasma\", name = \"KDE\") +\n  theme_void() +\n  labs(title = \"KDE Baseline Predictions\")\n\np3 <- ggplot() +\n  geom_sf(data = fishnet_eval, aes(fill = residual), color = NA) +\n  scale_fill_gradient2(low = \"blue\", mid = \"white\", high = \"red\", midpoint = 0) +\n  theme_void() +\n  labs(title = \"Poisson Residuals\")\n\np4 <- ggplot() +\n  geom_sf(data = fishnet_eval, aes(fill = kde_residual), color = NA) +\n  scale_fill_gradient2(low = \"blue\", mid = \"white\", high = \"red\", midpoint = 0) +\n  theme_void() +\n  labs(title = \"KDE Residuals\")\n\n(p1 + p2) / (p3 + p4) +\n  plot_annotation(\n    title = \"Model Comparison: Poisson vs KDE Baseline\",\n    subtitle = paste0(\n      \"Poisson — MAE: \", round(mae, 3), \" | RMSE: \", round(rmse, 3), \"\\n\",\n      \"KDE     — MAE: \", round(kde_mae, 3), \" | RMSE: \", round(kde_rmse, 3)\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}